run:
  timeout: 5m
  skip-dirs:
    - vendor
    - .git

linters:
  enable-all: true
  disable:
    - godox             # Don't warn on TODO comments
    - lll               # Line length - handled by gofmt

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/rossigee/mock-libvirtd
  govet:
    enable:
      - shadow
  revive:
    ignore-generated-header: true
    severity: warning
  exhaustive:
    default-signifies-exhaustive: false
  cyclop:
    max-complexity: 10
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
  funlen:
    lines: 60
    statements: 40
  misspell:
    locale: US
  nolintlint:
    require-explanation: true
    require-specific: true
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all"]
  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - cyclop
    - source: "^//go:build"
      linters:
        - nolintlint
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
